/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EscrowFactory {
      
    export type EscrowDealStruct = {buyer: AddressLike, seller: AddressLike, arbiter: AddressLike, amount: BigNumberish, state: BigNumberish, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type EscrowDealStructOutput = [buyer: string, seller: string, arbiter: string, amount: bigint, state: bigint, createdAt: bigint, updatedAt: bigint] & {buyer: string, seller: string, arbiter: string, amount: bigint, state: bigint, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface EscrowFactoryInterface extends Interface {
    getFunction(nameOrSignature: "confirmDelivery" | "createEscrow" | "dealCounter" | "deals" | "getDeal" | "getDealCount" | "raiseDispute" | "resolveDispute"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DeliveryConfirmed" | "DisputeRaised" | "DisputeResolved" | "EscrowCreated" | "EscrowFunded" | "Refunded"): EventFragment;

    encodeFunctionData(functionFragment: 'confirmDelivery', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'dealCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'deals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDealCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dealCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDealCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
  }

  
    export namespace DeliveryConfirmedEvent {
      export type InputTuple = [dealId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, timestamp: bigint];
      export interface OutputObject {dealId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeRaisedEvent {
      export type InputTuple = [dealId: BigNumberish, raisedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, raisedBy: string, timestamp: bigint];
      export interface OutputObject {dealId: bigint, raisedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [dealId: BigNumberish, winner: AddressLike, releasedToSeller: boolean, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, winner: string, releasedToSeller: boolean, timestamp: bigint];
      export interface OutputObject {dealId: bigint, winner: string, releasedToSeller: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [dealId: BigNumberish, buyer: AddressLike, seller: AddressLike, arbiter: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, buyer: string, seller: string, arbiter: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {dealId: bigint, buyer: string, seller: string, arbiter: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [dealId: BigNumberish, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, amount: bigint, timestamp: bigint];
      export interface OutputObject {dealId: bigint, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [dealId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [dealId: bigint, timestamp: bigint];
      export interface OutputObject {dealId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowFactory;
    waitForDeployment(): Promise<this>;

    interface: EscrowFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    confirmDelivery: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createEscrow: TypedContractMethod<
      [seller: AddressLike, arbiter: AddressLike, ],
      [bigint],
      'payable'
    >
    

    
    dealCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, arbiter: string, amount: bigint, state: bigint, createdAt: bigint, updatedAt: bigint }],
      'view'
    >
    

    
    getDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [EscrowFactory.EscrowDealStructOutput],
      'view'
    >
    

    
    getDealCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [dealId: BigNumberish, releaseToSeller: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [seller: AddressLike, arbiter: AddressLike, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'dealCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, arbiter: string, amount: bigint, state: bigint, createdAt: bigint, updatedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [EscrowFactory.EscrowDealStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDealCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [dealId: BigNumberish, releaseToSeller: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DeliveryConfirmed'): TypedContractEvent<DeliveryConfirmedEvent.InputTuple, DeliveryConfirmedEvent.OutputTuple, DeliveryConfirmedEvent.OutputObject>;
getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;

    filters: {
      
      'DeliveryConfirmed(uint256,uint256)': TypedContractEvent<DeliveryConfirmedEvent.InputTuple, DeliveryConfirmedEvent.OutputTuple, DeliveryConfirmedEvent.OutputObject>;
      DeliveryConfirmed: TypedContractEvent<DeliveryConfirmedEvent.InputTuple, DeliveryConfirmedEvent.OutputTuple, DeliveryConfirmedEvent.OutputObject>;
    

      'DisputeRaised(uint256,address,uint256)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,address,bool,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'EscrowCreated(uint256,address,address,address,uint256,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowFunded(uint256,uint256,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'Refunded(uint256,uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    
    };
  }